service: bgc-store-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1

  environment:
    tableName: products

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  create:
    handler: src/createProduct.main
    events:
      - http:
          path: products
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: src/getProduct.main
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    handler: src/listProduct.main
    events:
      - http:
          path: products
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: src/updateProduct.main
    events:
      - http:
          path: products/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    handler: src/deleteProduct.main
    events:
      - http:
          path: products/{id}
          method: delete
          cors: true
          authorizer: aws_iam

resources:
  - ${file(resources/api-gateway-errors.yml)}